import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        {
            type: 'doc',
            id: 'introduction',
            label: '🏠 Introduction',
        },
        {
            type: 'category',
            label: '🤖 AI',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'ai',
                },
            ],
        },
        {
            type: 'category',
            label: '🔗 Blockchain',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'blockchain',
                },
            ],
        },
        {
            type: 'category',
            label: '🌏 Browsers',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'browsers',
                },
            ],
        },
        {
            type: 'category',
            label: '⚡ Bundlers',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'bundlers',
                },
            ],
        },
        {
            type: 'category',
            label: '💻 Computers',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'computers',
                },
            ],
        },
        {
            type: 'category',
            label: '📦 Containers',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'containers',
                },
            ],
        },
        {
            type: 'category',
            label: '🎨 CSS',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'css',
                },
            ],
        },
        {
            type: 'category',
            label: '🗄️ Databases',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'databases',
                },
            ],
        },
        {
            type: 'category',
            label: '🧠 Data Structures',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'data-structures',
                },
            ],
        },
        {
            type: 'category',
            label: '🔄 Event Driven',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'event-driven',
                },
            ],
        },
        {
            type: 'category',
            label: '🐹 Go',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'go',
                },
            ],
        },
        {
            type: 'category',
            label: '📝 HTML',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'html',
                },
            ],
        },
        {
            type: 'category',
            label: '☕ Java',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'java',
                },
            ],
        },
        {
            type: 'category',
            label: '📜 JavaScript',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'javascript',
                },
            ],
        },
        {
            type: 'category',
            label: '🐧 Linux',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'linux',
                },
            ],
        },
        {
            type: 'category',
            label: '🛜 Network',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'network',
                },
            ],
        },
        {
            type: 'category',
            label: '🧲 Physics',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'physics',
                },
            ],
        },
        {
            type: 'category',
            label: '⚛️ React',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'react',
                },
            ],
        },
        {
            type: 'category',
            label: '🔐 Security',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'security',
                },
            ],
        },
        {
            type: 'category',
            label: '📂 Storage',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'storage',
                },
            ],
        },
        {
            type: 'category',
            label: '🟦 TypeScript',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'typescript',
                },
            ],
        },
    ],
};

export default sidebars;
