import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        {
            type: 'category',
            label: '🏠 Introduction',
            items: ['introduction'],
        },
        {
            type: 'category',
            label: '🤖 AI',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'ai',
                },
            ],
        },
        {
            type: 'category',
            label: '🌐 Browsers',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'browsers',
                },
            ],
        },
        {
            type: 'category',
            label: '⚡ Bundlers',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'bundlers',
                },
            ],
        },
        {
            type: 'category',
            label: '💻 Computers',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'computers',
                },
            ],
        },
        {
            type: 'category',
            label: '🎨 CSS',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'css',
                },
            ],
        },
        {
            type: 'category',
            label: '🗄️ Databases',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'databases',
                },
            ],
        },
        {
            type: 'category',
            label: '🔄 Event Driven',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'event-driven',
                },
            ],
        },
        {
            type: 'category',
            label: '🌐 Frontend',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'frontend',
                },
            ],
        },
        {
            type: 'category',
            label: '🐹 Go',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'go',
                },
            ],
        },
        {
            type: 'category',
            label: '📝 HTML',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'html',
                },
            ],
        },
        {
            type: 'category',
            label: '☕ Java',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'java',
                },
            ],
        },
        {
            type: 'category',
            label: '📜 JavaScript',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'javascript',
                },
            ],
        },
        {
            type: 'category',
            label: '🧲 Physics',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'physics',
                },
            ],
        },
        {
            type: 'category',
            label: '⚛️ React',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'react',
                },
            ],
        },
        {
            type: 'category',
            label: '🟦 TypeScript',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'typescript',
                },
            ],
        },
    ],
};

export default sidebars;
