# https://taskfile.dev

version: '3'

tasks:
    format-lint:
        desc: run all lint commands togeter
        cmds:
            - npx prettier --config .prettierrc --write .
            - npx eslint . --max-warnings=0
            - npx knip

    vale-lint:
        cmds:
            - docker run --rm -v $(pwd)/.github/vale/styles:/styles --pull=always --rm -v $(pwd):/docs -w /docs jdkato/vale .
    build:
        desc: Run all tasks requried for a full clean build
        # It's fine to run these tasks in parallel.
        deps:
            - format-lint
            - vale-lint
